const char* help_op_string =
"--Basic:--\n"
"+ -> X + Y\n"
"- -> X - Y\n"
"* -> X * Y\n"
"/ -> X / Y\n"
"--Trigonometry:--\n"
"sin -> sin(X) | sine\n"
"cos -> cos(X) | cosine\n"
"tan -> tan(X) | tangent\n"
"asin -> asin(X) | sine-1\n"
"acos -> acos(X) | cosine-1\n"
"atan -> atan(X) | tangent-1\n"
"dtr -> dtr(X) | Degrees to radians\n"
"rtd -> rtd(X) | Radians to degrees\n"
"--Powers:--\n"
"sqrt -> sqrt(X) | Square root\n"
"nrt -> Xth root of Y\n"
"^ -> Y^X | Y to the Xth power\n"
"ln -> ln(X) | Natural logarithm\n"
"log -> log(X) | Common logarithm\n"
"logn -> logY(X) | Logarithm base Y of X\n"
"--Extras:--\n"
"ceil -> ceil(X)\n"
"floor -> floor(X)\n"
"absv -> |X|\n"
;
